// The camera pipelines, checked two ways.
//
// 1. Semantically equivalent to what the predecessor produced. Not byte-equal:
//    gst_parse_launch does not care what order properties appear in, and unlike
//    the result wire format no external consumer reads these strings. Demanding
//    byte-equality would constrain the builder for no benefit and fail on
//    changes that mean nothing.
//
// 2. GStreamer actually parses them. A string that merely looks right is worth
//    little; this is the check the predecessor could not make without a camera.

#include "TestHarness.hpp"

#include <gst/gst.h>

#include <algorithm>
#include <map>
#include <string>
#include <vector>

#include "media/gst/ElementAvailability.hpp"
#include "media/pipeline/CameraPipelines.hpp"
#include "media/stream/RetryPolicy.hpp"
#include "media/recording/RecordingSession.hpp"
#include "media/source/RtspEncodedSource.hpp"
#include "media/stream/SnapshotGrabber.hpp"

using namespace visora::media;

namespace {

// One element or caps filter, decomposed.
struct Node {
    std::string head;                            // factory name, or the caps string
    std::map<std::string, std::string> properties;
};

std::string trim(const std::string& text) {
    const auto begin = text.find_first_not_of(" \t");
    if (begin == std::string::npos) return {};
    const auto end = text.find_last_not_of(" \t");
    return text.substr(begin, end - begin + 1);
}

// Splits on a delimiter, ignoring anything inside double quotes — an RTSP URL
// may contain almost anything.
std::vector<std::string> splitOutsideQuotes(const std::string& text, const std::string& delimiter) {
    std::vector<std::string> parts;
    std::string current;
    bool inQuotes = false;
    for (std::size_t i = 0; i < text.size(); ++i) {
        const char c = text[i];
        if (c == '\\' && i + 1 < text.size()) {
            current.push_back(c);
            current.push_back(text[++i]);
            continue;
        }
        if (c == '"') inQuotes = !inQuotes;
        if (!inQuotes && text.compare(i, delimiter.size(), delimiter) == 0) {
            parts.push_back(trim(current));
            current.clear();
            i += delimiter.size() - 1;
            continue;
        }
        current.push_back(c);
    }
    parts.push_back(trim(current));
    return parts;
}

std::vector<Node> parseLaunch(std::string description) {
    description = trim(description);
    if (!description.empty() && description.front() == '(') {
        description = trim(description.substr(1, description.size() - 2));
    }

    std::vector<Node> nodes;
    for (const std::string& segment : splitOutsideQuotes(description, "!")) {
        if (segment.empty()) continue;
        // A caps filter has no properties and contains a '/' in its media type.
        if (segment.find('=') == std::string::npos || segment.find('/') < segment.find(' ')) {
            nodes.push_back(Node{segment, {}});
            continue;
        }
        const std::vector<std::string> tokens = splitOutsideQuotes(segment, " ");
        Node node;
        node.head = tokens.empty() ? std::string() : tokens.front();
        for (std::size_t i = 1; i < tokens.size(); ++i) {
            const auto equals = tokens[i].find('=');
            if (equals == std::string::npos) continue;
            node.properties[tokens[i].substr(0, equals)] = tokens[i].substr(equals + 1);
        }
        nodes.push_back(std::move(node));
    }
    return nodes;
}

void expectEquivalent(const std::string& got, const std::string& want) {
    const std::vector<Node> a = parseLaunch(got);
    const std::vector<Node> b = parseLaunch(want);

    if (a.size() != b.size()) {
        ::visora::test::reportFailure(__FILE__, __LINE__,
                                      "element count differs: " + std::to_string(a.size()) +
                                          " vs " + std::to_string(b.size()) + "\n    got : " +
                                          got + "\n    want: " + want);
        return;
    }
    for (std::size_t i = 0; i < a.size(); ++i) {
        if (a[i].head != b[i].head) {
            ::visora::test::reportFailure(__FILE__, __LINE__,
                                          "element " + std::to_string(i) + " is '" + a[i].head +
                                              "', expected '" + b[i].head + "'");
            continue;
        }
        if (a[i].properties != b[i].properties) {
            std::string detail = "properties of '" + a[i].head + "' differ\n    got :";
            for (const auto& [k, v] : a[i].properties) detail += " " + k + "=" + v;
            detail += "\n    want:";
            for (const auto& [k, v] : b[i].properties) detail += " " + k + "=" + v;
            ::visora::test::reportFailure(__FILE__, __LINE__, detail);
        }
    }
}

// Reference strings from the predecessor's stream::launchStringForCamera,
// generated by compiling and running it.
const char* kPredecessorH264 =
    R"(( rtspsrc name=src location="rtsp://user:pa\"ss@10.0.0.1/stream" latency=300 protocols=tcp ! application/x-rtp,media=video,encoding-name=H264 ! rtph264depay ! h264parse config-interval=-1 ! rtph264pay config-interval=1 name=pay0 pt=96 ))";

const char* kPredecessorH265 =
    R"(( rtspsrc name=src location="rtsp://user:pa\"ss@10.0.0.1/stream" latency=300 protocols=tcp ! application/x-rtp,media=video,encoding-name=H265 ! rtph265depay ! h265parse config-interval=-1 ! rtph265pay config-interval=1 name=pay0 pt=96 ))";

const char* kPredecessorH264Latency800 =
    R"(( rtspsrc name=src location="rtsp://user:pa\"ss@10.0.0.1/stream" latency=800 protocols=tcp ! application/x-rtp,media=video,encoding-name=H264 ! rtph264depay ! h264parse config-interval=-1 ! rtph264pay config-interval=1 name=pay0 pt=96 ))";

CameraSource testCamera(Codec codec) {
    CameraSource camera;
    camera.id = "cam-1";
    camera.rtspUrl = "rtsp://user:pa\"ss@10.0.0.1/stream";
    camera.codec = codec;
    return camera;
}

bool gstreamerParses(const std::string& description, std::string* error) {
    static bool initialised = false;
    if (!initialised) {
        gst_init(nullptr, nullptr);
        initialised = true;
    }
    GError* err = nullptr;
    GstElement* element = gst_parse_launch(description.c_str(), &err);
    if (err != nullptr) {
        *error = err->message;
        g_error_free(err);
        if (element != nullptr) gst_object_unref(element);
        return false;
    }
    if (element == nullptr) {
        *error = "gst_parse_launch returned nothing";
        return false;
    }
    gst_object_unref(element);
    return true;
}

}  // namespace

VS_TEST(h264_restream_matches_the_predecessor) {
    RestreamOptions options;
    options.latencyMs = 100;  // below the floor
    expectEquivalent(restreamLaunch(testCamera(Codec::H264), options), kPredecessorH264);
}

VS_TEST(h265_restream_matches_the_predecessor) {
    RestreamOptions options;
    options.latencyMs = 100;
    expectEquivalent(restreamLaunch(testCamera(Codec::H265), options), kPredecessorH265);
}

VS_TEST(a_latency_above_the_floor_is_kept) {
    RestreamOptions options;
    options.latencyMs = 800;
    expectEquivalent(restreamLaunch(testCamera(Codec::H264), options), kPredecessorH264Latency800);
}

VS_TEST(latency_is_floored_at_300ms) {
    // Not a rounding preference. A camera's IDR frame is a burst of hundreds of
    // TCP packets; on a busy board the whole burst misses a short deadline and
    // the jitter buffer discards its tail, so every viewer gets a stream that
    // will not decode. Lowering this floor breaks live viewing under load, in a
    // way that looks like a camera fault.
    RestreamOptions options;
    options.latencyMs = 40;
    const std::string launch = restreamLaunch(testCamera(Codec::H264), options);
    VS_CHECK(launch.find("latency=300") != std::string::npos);
}

VS_TEST(an_unknown_codec_produces_nothing_rather_than_a_broken_pipeline) {
    VS_CHECK(restreamLaunch(testCamera(Codec::Unknown), RestreamOptions{}).empty());
}

VS_TEST(the_url_is_quoted_so_a_password_cannot_break_the_syntax) {
    CameraSource camera = testCamera(Codec::H264);
    camera.rtspUrl = "rtsp://user:p@ss word!x@10.0.0.1/stream";
    const std::string launch = restreamLaunch(camera, RestreamOptions{});
    // The exclamation mark inside the URL must not be read as a link operator.
    std::string error;
    VS_CHECK(gstreamerParses(launch, &error));
    if (!error.empty()) {
        ::visora::test::reportFailure(__FILE__, __LINE__, "gst_parse_launch: " + error);
    }
}

VS_TEST(gstreamer_parses_what_we_build) {
    // The check the predecessor could not make without a camera attached: not
    // "does the string look right" but "does GStreamer accept it".
    for (const Codec codec : {Codec::H264, Codec::H265}) {
        const std::string launch = restreamLaunch(testCamera(codec), RestreamOptions{});
        std::string error;
        if (!gstreamerParses(launch, &error)) {
            ::visora::test::reportFailure(__FILE__, __LINE__,
                                          std::string("gst_parse_launch rejected the ") +
                                              toString(codec) + " pipeline: " + error);
        }
    }
}

VS_TEST(the_mount_path_is_unchanged) {
    VS_CHECK(mountPath("cam-1") == "/cameras/cam-1");
}

// --- reconnect backoff -------------------------------------------------------
//
// Pure arithmetic, so the curve is asserted rather than observed. The
// predecessor's equivalent could only be checked by unplugging a camera and
// watching a log.

VS_TEST(backoff_doubles_then_stops_at_the_ceiling) {
    RetryPolicy policy;
    policy.initialMs = 1000;
    policy.maxMs = 30000;

    VS_CHECK_EQ(policy.delayFor(0), 1000u);
    VS_CHECK_EQ(policy.delayFor(1), 2000u);
    VS_CHECK_EQ(policy.delayFor(2), 4000u);
    VS_CHECK_EQ(policy.delayFor(3), 8000u);
    VS_CHECK_EQ(policy.delayFor(4), 16000u);
    VS_CHECK_EQ(policy.delayFor(5), 30000u);   // clamped
    VS_CHECK_EQ(policy.delayFor(50), 30000u);  // stays clamped
}

VS_TEST(a_very_large_attempt_count_cannot_overflow) {
    // A camera unreachable for days reaches a large attempt count. Computing
    // the delay by exponentiation and clamping afterwards would wrap round to a
    // tiny value and turn the backoff into a hot loop against a dead device.
    RetryPolicy policy;
    policy.initialMs = 1000;
    policy.maxMs = 30000;
    for (std::uint32_t attempt : {100u, 1000u, 100000u}) {
        VS_CHECK_EQ(policy.delayFor(attempt), 30000u);
    }
}

VS_TEST(a_ceiling_below_the_first_delay_is_honoured) {
    RetryPolicy policy;
    policy.initialMs = 5000;
    policy.maxMs = 1000;
    VS_CHECK_EQ(policy.delayFor(0), 1000u);
}

// --- snapshot ----------------------------------------------------------------

VS_TEST(the_snapshot_pipeline_is_unwrapped_and_parses) {
    setElementProbe(nullptr);  // ask the real GStreamer registry
    SnapshotOptions options;
    const std::string launch = snapshotLaunch("rtsp://cam/1", options);
    if (launch.empty()) {
        // No JPEG encoder installed anywhere. Reporting that is the correct
        // behaviour, and there is nothing further to assert here.
        std::fprintf(stderr, "    (no JPEG encoder on this machine; skipped)\n");
        return;
    }

    // NOT parenthesised. gst_parse_launch returns a GstBin rather than a
    // GstPipeline for a wrapped description, and set_state on that goes
    // nowhere — the failure appears much later, as a timeout.
    VS_CHECK(launch.front() != '(');

    GError* error = nullptr;
    GstElement* pipeline = gst_parse_launch(launch.c_str(), &error);
    if (error) {
        ::visora::test::reportFailure(__FILE__, __LINE__, error->message);
        g_error_free(error);
    }
    VS_CHECK(pipeline != nullptr);
    if (pipeline) {
        VS_CHECK(GST_IS_PIPELINE(pipeline));
        gst_object_unref(pipeline);
    }
}

VS_TEST(the_snapshot_latency_floor_is_applied) {
    setElementProbe([](const std::string&) { return true; });
    SnapshotOptions options;
    options.latencyMs = 200;  // below the floor: a burst-delivered IDR is
                              // truncated at this value and decodes green
    const std::string launch = snapshotLaunch("rtsp://cam/1", options);
    VS_CHECK(launch.find("latency=" + std::to_string(kSnapshotMinimumLatencyMs)) !=
             std::string::npos);

    options.latencyMs = 2000;  // above it: honoured as asked
    VS_CHECK(snapshotLaunch("rtsp://cam/1", options).find("latency=2000") !=
             std::string::npos);
    setElementProbe(nullptr);
}

VS_TEST(the_snapshot_sink_pulls_one_frame_at_a_time) {
    setElementProbe([](const std::string&) { return true; });
    const std::string launch = snapshotLaunch("rtsp://cam/1", SnapshotOptions{});
    // Warm-up counts frames rather than sleeping, which only works because each
    // pull advances the decoder exactly one frame.
    VS_CHECK(launch.find("max-buffers=1") != std::string::npos);
    VS_CHECK(launch.find("drop=false") != std::string::npos);
    // drop-on-latency must never appear: dropping the tail of a keyframe burst
    // is what turns a 1080p H.265 snapshot green.
    VS_CHECK(launch.find("drop-on-latency") == std::string::npos);
    setElementProbe(nullptr);
}

// --- the shared source and the recorder --------------------------------------
//
// Both are strings until GStreamer accepts them. Asserting the text alone is
// how a pipeline that merely looks right reaches a board.

VS_TEST(the_shared_source_pipeline_parses_for_both_codecs) {
    RtspSourceOptions options;
    for (const Codec codec : {Codec::H264, Codec::H265}) {
        const std::string launch = RtspEncodedSource::launchFor("rtsp://cam/1", codec, options);
        VS_CHECK(!launch.empty());
        std::string error;
        if (!gstreamerParses(launch, &error)) {
            ::visora::test::reportFailure(__FILE__, __LINE__, error + "  in: " + launch);
        }
        // config-interval=-1 repeats the parameter sets with every keyframe, so
        // a consumer attaching mid-stream can decode from its first keyframe
        // instead of waiting for the camera to resend them.
        VS_CHECK(launch.find("config-interval=-1") != std::string::npos);
        // Never drop: an access unit dropped here corrupts the stream for EVERY
        // consumer of this camera, not just the slow one.
        VS_CHECK(launch.find("drop=false") != std::string::npos);
    }
    VS_CHECK(RtspEncodedSource::launchFor("rtsp://cam/1", Codec::Unknown, options).empty());
}

VS_TEST(the_source_latency_floor_is_applied) {
    RtspSourceOptions options;
    options.latencyMs = 50;  // below the floor
    const std::string launch = RtspEncodedSource::launchFor("rtsp://cam/1", Codec::H264, options);
    // 300 ms, the same floor as the restream and the snapshot: below it a
    // burst-delivered keyframe is truncated and every consumer sees a corrupt
    // IDR at once.
    VS_CHECK(launch.find("latency=300") != std::string::npos);
}

VS_TEST(the_recording_pipeline_parses) {
    RecordingOptions options;
    options.segmentSeconds = 10;
    for (const Codec codec : {Codec::H264, Codec::H265}) {
        const std::string launch = RecordingSession::launchFor("cam", codec, options);
        std::string error;
        if (!gstreamerParses(launch, &error)) {
            ::visora::test::reportFailure(__FILE__, __LINE__, error + "  in: " + launch);
        }
    }
}

VS_MAIN()
